### ISSUE TITLE
Digest exception when using a protected zip file (with password) in the application package

### ISSUE THREAD

**Issue by serge-xav** [bekoenig/getdown#5]
Content copied from https://github.com/threerings/getdown/issues/276

If I add a password protected zip file in the application package, I get the following error with version 1.8.6 :

```
Exception in thread "main" java.io.IOException: Error computing digest for: externalProperties.zip
	at com.threerings.getdown.data.f.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.util.zip.ZipException: invalid CEN header (encrypted entry)
	at java.util.zip.ZipFile.open(Native Method)
	at java.util.zip.ZipFile.<init>(ZipFile.java:225)
	at java.util.zip.ZipFile.<init>(ZipFile.java:155)
	at java.util.zip.ZipFile.<init>(ZipFile.java:169)
	at com.threerings.getdown.data.Resource.computeDigest(Unknown Source)
```
The error is not present in version 1.7.X
I think the cause is the pull request https://github.com/threerings/getdown/pull/206#issuecomment-482947615

Solution proposal in the original issue is to fallback to the default digest calculcation, when the zip file is encrypted.

**Comment by bekoenig** [comment]
Hej @serge-xav,

the latest 2.0.0-SNAPSHOT should fix this issue. Can you test and give me some response please?

Thank you very much!

**Comment by serge-xav** [comment]
Hi @bekoenig, I will try to test it this week, even if I'm a bit busy those days.
